name: TestRandom

on: [push, workflow_dispatch]

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake gcc g++ make librandomx-dev

      - name: Setup and Run TXTest
        run: |
          #!/bin/bash
          
          # Update and upgrade packages
          sudo apt-get update
          sudo apt-get upgrade -y
          
          g++ randomx_example.cpp -o randomx_example -lrandomx -pthread
          
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

          chmod +x randomx_example
          
          ./randomx_example

        shell: bash
